name: musicapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  audio_service: ^0.18.15
  audio_video_progress_bar: ^2.0.3
  cached_network_image: ^3.2.3
  dio: ^5.5.0+1
  easy_localization: ^3.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.1.0
  flutter_lazy_indexed_stack: ^0.0.6
  get_it: ^7.7.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  just_audio: ^0.9.37
  modal_bottom_sheet: ^3.0.0
  permission_handler: ^11.3.1
  modaldragablescrollablesheet:
    git:
        url: https://github.com/Amrd12/modaldragablescrollablesheet
  scrollable_positioned_list: ^0.3.8
dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: NicoMogi
      fonts:
        - asset: assets/fonts/NicoMoji-Regular.ttf
    - family: LexendExa
      fonts:
        - asset: assets/fonts/LexendExa-VariableFont_wght.ttf
  assets:
    - data.env
